server:
  port: 8102

oss:
  accessKeyId: ****
  accessKeySecret: ****
  bucketName: keithw-bucket
  endPoint: oss-cn-shenzhen.aliyuncs.com

spring:
  application:
      name: haircut-pro
  datasource:
    druid:
      url: jdbc:mysql://***:3306/haircut-pro?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: ****
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
  redis:
    host: ****
    port: 6379
    database: 0
    timeout: 1000s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    resources:
      static-locations: classpath:/static

    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait: -1
        # 最大活跃连接数，负数为不限制
        max-active: -1
    password: ****
  #    cache:
#      redis:
#        time-to-live: -1 #毫秒
  rabbitmq:
    host: ****
    port: 5672
    username: ****
    password: ****


  servlet:
    multipart:
      max-file-size: 100368443
      max-request-size: 150368443


#  thymeleaf:
#      cache: false
#      mode: HTML5
#      encoding: UTF-8
#      content-type: text/html

mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

keyGenerator:
  snowflake:
    workerId: 20 #进程ID，每个实例都要设置不同的值，范围：0-1023
    maxTolerateTime: 1500 #最大容忍时钟回退时间，单位：毫秒


  spring:
    thymeleaf:
      cache: false

#设置静态资源路径，多个以逗号分隔
spring.resources.static-locations: classpath:static/,file:static/
